### ISSUE TITLE
Addressable::URI::InvalidURIError: Cannot have a path with two leading slashes without an authority set: '///token'

### ISSUE THREAD

**Issue by donaldding** [bayetech/easemob#1]
ruby 2.2.2p95
Rails 4.2.6
Mac OS X 10.10.5
已经在config下添加了easemob配置

在irb测试添加账号的时候出现错误

irb(main):028:0* Easemob.create_user("aaaa","123456")
Addressable::URI::InvalidURIError: Cannot have a path with two leading slashes without an authority set: '///token'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/addressable-2.5.0/lib/addressable/uri.rb:2429:in `validate'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/addressable-2.5.0/lib/addressable/uri.rb:2357:in `defer_validation'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/addressable-2.5.0/lib/addressable/uri.rb:2263:in `omit'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/request.rb:145:in `headline'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/request.rb:110:in `stream'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/connection.rb:74:in `send_request'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/client.rb:63:in `perform'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/client.rb:41:in `request'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/http-2.1.0/lib/http/chainable.rb:26:in `post'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/easemob-0.3.2/lib/easemob/token.rb:5:in `block in refresh'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/easemob-0.3.2/lib/easemob/token.rb:4:in `refresh'
... 14 levels...
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/donaldding/projects/rails/hardware_mall/bin/rails:9:in `<top (required)>'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/donaldding/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by donaldding** [comment]
😯 忘了把配置文件放在initializers里了
